name: Hugging Face Exercise

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - name: Change directory to backend
      run: cd backend
    - name: Install dependencies
      run: npm install
    - name: Test backend
      run: npm run test:all