name: Hugging Face Exercise CI

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    services: 
      elasticsearch:
        image: elasticsearch:7.12.1
        ports:
        - 9200:9200
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 15.x
      uses: actions/setup-node@master
      with:
        version: 15.x

    - name: Install dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Launch all tests
      working-directory: ./backend
      run: |
        npm run test:all
      env:
        CI: true

