name: Hugging Face Exercise CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.js 15.x
      uses: actions/setup-node@master
      with:
        version: 15.x

    - name: Install dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Launch all tests
      working-directory: ./backend
      run: |
        npm run test:all

